export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#004e5c",
        "surface": "#faf8ff",
        "surface-container": "#eaedff",
        "error-container": "#ffdad6",
        "surface-bright": "#faf8ff",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#4cd7f6",
        "inverse-on-surface": "#eef0ff",
        "primary-fixed": "#dae2fd",
        "on-primary-fixed": "#17521B",
        "on-primary-fixed-variant": "#3f465c",
        "on-error": "#ffffff",
        "surface-tint": "#565e74",
        "tertiary-fixed": "#acedff",
        "on-secondary-container": "#54647a",
        "surface-variant": "#dae2fd",
        "on-background": "#17521B",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "primary-container": "#17521B",
        "secondary-fixed": "#d3e4fe",
        "on-secondary-fixed-variant": "#38485d",
        "surface-container-high": "#e2e7ff",
        "on-primary-container": "#7c839b",
        "primary": "#000000",
        "secondary-container": "#d0e1fb",
        "surface-container-highest": "#dae2fd",
        "on-surface": "##17521B",
        "on-error-container": "#93000a",
        "surface-dim": "#d2d9f4",
        "inverse-surface": "#283044",
        "on-surface-variant": "#45464d",
        "background": "#faf8ff",
        "inverse-primary": "#bec6e0",
        "on-tertiary-fixed": "#001f26",
        "on-secondary": "#ffffff",
        "outline": "#76777d",
        "surface-container-low": "#f2f3ff",
        "tertiary-container": "#001f26",
        "primary-fixed-dim": "#bec6e0",
        "secondary-fixed-dim": "#b7c8e1",
        "secondary": "#505f76",
        "tertiary": "#000000",
        "outline-variant": "#c6c6cd",
        "on-tertiary-container": "#0090a9",
        "on-secondary-fixed": "#0b1c30",
        "surface-container-lowest": "#ffffff",

      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
